Error on bad type
bwasti/mebm pull request #7
Opened 2021-01-31 12:54 UTC by hozfia

i added simple function to check for bad type files and display message of the file(s) name witch are not supported.  

the supported type are listed in array , i don't know if this proper way because it mean that you need to list all the types you are supporting , i listed a few of them witch ware listed in other parts of the code 

here screenshot 
![memb](https://user-images.githubusercontent.com/48630338/106384534-026f5780-63d4-11eb-9837-95d8e0527591.png)

2021-02-02 13:45 UTC, bwasti requested changes
Looks great!  I appreciate the contribution.

The only main change I'd like to see is to use the `ext_map` instead of `supportedType` (the other types are for exporting and it's fine to ignore them).

If you'd like to remove the `alert`, there's a `popup` function.

2021-02-02 13:45 UTC, bwasti commented on script.js
> +  let supportedType = [
Let's just use the `ext_map` on line 1192. We can make that global and then use `if (!(extension in ext_map)) {`.

2021-02-02 13:45 UTC, bwasti commented on script.js
> +  + badUserExtensions.map((ext)=>"- "+ext.name).join('\n')):"";
```suggestion
  if (badUserExtensions.length > 0) {
    const badFiles = badUserExtensions.map((ext)=>"- "+ext.name).join('\n');
    alert('the file(s) you uploaded are not supported \n' + badFiles);
  }
```

2021-02-04 09:56 UTC, hozfia commented
i added those changes : 
make ext_map global variable , then use popup instead of using browser alert

2021-02-05 02:24 UTC, bwasti approved these changes
Awesome!

2021-02-05 02:25 UTC, merged